// Generated by LwM2M2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: 1 LwM2M object definitions from 3303.xml
//          https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/3303.xml
// OMA LwM2M registry: https://github.com/OpenMobileAlliance/lwm2m-registry
// Objects are packs; executable resources are nested *_Execute command packs.
// LwM2M ObjectIDs / resource ids address the SOURCE's tree and are kept as constants and attributes;
// the AdHoc pack ids in the Dashboard are assigned by AdHocAgent.
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.lwm2m {
    /**
        <see cref = 'Temperature'/>
        <see cref = 'Temperature.Reset_Min_and_Max_Measured_Values_Execute'/>
    */
    public interface LwM2M_Temperature {

        /** Permissive defaults for LwM2M-sourced data: the registry states no ceiling for instances or blobs. */
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        LwM2M Objlnk value: a reference to an object instance, 16-bit object id and 16-bit instance id.
        Used only as a field type, so it stays a non-transmittable value pack.
        */
        class ObjectLink {
            ushort object_id;
            ushort instance_id;
        }

        // ═════════════════════════ 3303.xml: Temperature (urn:oma:lwm2m:ext:3303:1.1) ═════════════════════════
        /**
        This IPSO object should be used with a temperature sensor to report a temperature measurement.  It also
        provides resources for minimum/maximum measured values and the minimum/maximum range that can be measured by
        the temperature sensor. An example measurement unit is degrees Celsius.
        */
        class Temperature {
            public const ushort lwm2m_object_id          = 3303;
            public const string lwm2m_urn                = "urn:oma:lwm2m:ext:3303:1.1";
            public const string lwm2m_version            = "1.0";
            public const string lwm2m_object_version     = "1.1";
            public const bool   lwm2m_multiple_instances = true;
            public const bool   lwm2m_mandatory          = false;

            /**
            Last or Current Measured Value from the Sensor.
            */
            [ResourceId(5700), Operations("R"), Mandatory] double Sensor_Value;

            /**
            The minimum value measured by the sensor since power ON or reset.
            */
            [ResourceId(5601), Operations("R")] double? Min_Measured_Value;

            /**
            The maximum value measured by the sensor since power ON or reset.
            */
            [ResourceId(5602), Operations("R")] double? Max_Measured_Value;

            /**
            The minimum value that can be measured by the sensor.
            */
            [ResourceId(5603), Operations("R")] double? Min_Range_Value;

            /**
            The maximum value that can be measured by the sensor.
            */
            [ResourceId(5604), Operations("R")] double? Max_Range_Value;

            /**
            Measurement Units Definition.
            */
            [ResourceId(5701), Operations("R")] string Sensor_Units;

            /**
            The application type of the sensor or actuator as a string depending on the use case.
            */
            [ResourceId(5750), Operations("RW")] string Application_Type;

            /**
            The timestamp of when the measurement was performed.
            */
            [ResourceId(5518), Operations("R")] DateTime? Timestamp;

            /**
            Fractional part of the timestamp when sub-second precision is used (e.g., 0.23 for 230 ms).
            */
            [Range("0..1"), ResourceId(6050), Operations("R"), Units("s")] double? Fractional_Timestamp;

            /**
            Measurement quality indicator reported by a smart sensor. 0: UNCHECKED No quality checks were done because
            they do not exist or can not be applied. 1: REJECTED WITH CERTAINTY The measured value is invalid. 2: REJECTED
            WITH PROBABILITY The measured value is likely invalid. 3: ACCEPTED BUT SUSPICIOUS The measured value is likely
            OK. 4: ACCEPTED The measured value is OK. 5-15: Reserved for future extensions. 16-23: Vendor specific
            measurement quality.
            */
            [MinMax(0, 23), ResourceId(6042), Operations("R")] byte? Measurement_Quality_Indicator;

            /**
            Measurement quality level reported by a smart sensor. Quality level 100 means that the measurement has fully
            passed quality check algorithms. Smaller quality levels mean that quality has decreased and the measurement
            has only partially passed quality check algorithms. The smaller the quality level, the more caution should be
            used by the application when using the measurement. When the quality level is 0 it means that the measurement
            should certainly be rejected.
            */
            [MinMax(0, 100), ResourceId(6049), Operations("R")] byte? Measurement_Quality_Level;

            /**
            Reset the Min and Max Measured Values to Current Value.
            Execute operation on resource 5605 (Reset Min and Max Measured Values); sent by the Server to the Client.
            */
            [ResourceId(5605), Operations("E")] public class Reset_Min_and_Max_Measured_Values_Execute {
                /** Optional LwM2M Execute arguments, in the `<id>='<value>'` text form of the specification. */
                [D(+1024)] string? execute_arguments;
            }
        }

        // ═════════════════════════ topology ═════════════════════════

        // LwM2M has exactly two roles: the Server manages the Client (the device). Object instances travel in
        // both directions (Read / Write / Observe / Notify); Execute is always Server -> Client.

        // LwM2M Server (management side, Left)
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        // LwM2M Client (the device, Right)
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        interface Management : Connects<Server, Client> {
            // Object instances: either side may send any object (Read/Write/Observe/Notify payloads).
            [_____lr_____<Temperature>]
            struct Objects { }

            // Execute operations: the Server invokes an executable resource on the Client.
            [l____________<Temperature.Reset_Min_and_Max_Measured_Values_Execute>]
            struct Execute { }
        }

        // ═════════════════════════ LwM2M resource metadata attributes ═════════════════════════

        // AdHoc custom attributes: the generator materialises them as constants next to the field, so the
        // resource id, allowed operations, units and value range stay available at runtime.

        /** LwM2M resource id (the `/object/instance/&lt;resource&gt;` path segment). */
        public class ResourceIdAttribute : Attribute { public ResourceIdAttribute(int id) { } }

        /** Allowed operations: R, W, RW or E. */
        public class OperationsAttribute : Attribute { public OperationsAttribute(string operations) { } }

        /** SenML unit of the value, as written in the registry. */
        public class UnitsAttribute : Attribute { public UnitsAttribute(string units) { } }

        /** RangeEnumeration text that is not a plain integer range (float ranges, value lists, prose). */
        public class RangeAttribute : Attribute { public RangeAttribute(string range) { } }

        /** The resource is mandatory in every instance of the object. */
        public class MandatoryAttribute : Attribute { }

    }
}
